### ISSUE TITLE
Vignette manual example fails at add_split

### ISSUE THREAD

**Issue by alansz** [adayim/consort#1] opened 2021-12-09 15:59 UTC
R version 3.6.0 (2019-04-26), tidyverse. The following code from the vignette (with the pipe tweaked):

```
library(consort)
txt1 <- "Population (n=300)"
txt1_side <- "Excluded (n=15):\n\u2022 MRI not collected (n=3)\n\u2022 Tissues not collected (n=4)\n\u2022 Other (n=8)"
g <- add_box(txt = txt1) %>%
  add_side_box(txt = txt1_side) %>%
  add_box(txt = "Randomized (n=200)") %>%
  add_split(txt = c("Arm A (n=100)", "Arm B (n=100)"))

```
Fails at add_split with:

Error in get_dist(y_s, y_e) : 
  (list) object cannot be coerced to type 'double'

**Comment by adayim** [comment] 2021-12-09 17:44
Thanks for reporting this. I can replicate the problem. I think this is caused by the different version of `grid` package. Will submit a new one to address this issue.

**Comment by adayim** [comment] 2021-12-10 23:05
Can you install package from Github? I have fixed this and should work now. I will publish to CRAN if this works for you.

**Comment by alansz** [comment] 2021-12-20 17:26
Yes, the vignette code now works. Thank you!

 - Alan

Quoting Alim Dayim ***@***.***):

**Comment by adayim** [comment] 2021-12-21 09:16
Thank you for the feedback, the package in the CRAN now and I am closing this issue.

**Closed by adayim** 2021-12-21 09:16 UTC
Labels: enhancement
